language: node_js
node_js:
- 11.10.1
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: KMtRJszS7HBiuBoBpgEdRTviBJPas28fqnERaHBsOxkLqCKKmZASw2roMorVKROhuEc7306VtvRoV/G18GUoCwrAkwarNZB8qImzbu4ORSzDqmEqzRkb3C/JX2LDlPoJw6Rss2vDI13Im7gSSkgyP0ZU7/YknN42N7Rz4ePMKpjJOM7mkXxV5GRZFJAyhKjvSkBAJCBLn5GtQ65xcK75Z67LsQnEM/ONBWf7KT9C4Gx6IkPUJnF8fBYtUvFRkdYmlk9mOSHWk3NWMxpt/ZpbH5/S/Kyey33Csmwuc0+f9weHXAgxxZpr4wLmI7w/BUtc6rvFAJ/YEmOoYT8tc2fua4hEjDnFYRDIEs3a/VAvpl7MIl5OlSDJ76aSyEZDe1nKWj+V/T50hl9/hT/Gvp3sT5qn9AZ4lzrsEFKiuz6plRBoaWsrZlFYtjaNPXF2PPmJiAZ2LC6MxeFsg4Z/cyDLGri250tatOvzMjFedGYsK98l1A6IR+e+CXsXvezL7fNYT7wR8p7z9D0rxPOEqzHZxtuNZ5/mLEEuM6Y45Y9gCycNh55oPf9fr1VuOEUhfEfwbiTuFoKYpfCBA+niLOvU8ZRGJ8Fa/puLCvbowSSm9OHy0OXbjlqI0kjyTxQhvOMpHok8oiWk9Jqf8kRv/2uQCN5nkZZHpmYZbnHaAviL0Yk=
  app: floating-wave-88429
  on:
    repo: Btan579/Jam-Soon-Client
