language: node_js
node_js:
- 11.10.1
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: kg1BHxwuqbZLvWM9Gsqm14w09mJhGasH6K8XdgY9KSpBUkda5hDC+aGb70GAKp8EkXZqwtvp+zn1Q/wL5Huko68yGqu/7130RKxn5A2sNXgaHXmTnIcAnGTCZHHB74A6/E9JFX3eKDqyry9CmkiWMYMtWHdDkj0Z/TS+2wvH5BscH0Yxe5JPsJcIHDflMx8d1YqomxvhoLyb4WxoAxRolUzgU64PDO5QltKuwzilTDlm9lm+O7RxDg0578A0qJUaa7BYDff1nVnbYUWlm6Q6emKmyu5c/ObS4rAnEt9cyo8luQ+Cr0EChps2VdsiQ9nsSsr8btW7dZwJVw+eYH84okib4zKiN2PVaa37FCrj9k8BpckDbddbvq7IM+XsStbIH0JpkhiQIXfLl6k6DNFbIZrp6hDUtrNje8yCH9UMLqwLZk6LHawJBypQuZd8iXRnn+Irl2RtnvDiF24+rwM4GqvGhQeTSPdVO1uISPCmwVqccRjNBjeLJHZeOE7GTgecOgZPscSTWYZQQEROS2VDupYs9FMMnzSkNWphigaaOWJK/i51zUH67WfOyLLFKLKTws0dAEwOWf+yhM6LZPJ/URPCry58klznyH7TJe1Zf1umK2Pp66RF4hUaQwCBru4nA5dFw8sJqe4eO2uGoZnHWrHuUguh8m3Y/bXP3U5z1u4=
  app: floating-wave-88429
  on:
    repo: Btan579/Jam-Soon-Client
