language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: HLttboUZ+6dpbaenHdFkN4qSb2jvnvG/JVuwWmJEkR6IKhmE3zR/fSnMhY9/k4H9L8KGzPeGZcIv1UztvnxyOaiGLyFsIInTNqUlyrL+NSVZGBz1ozl0utTf0Ps7GoVDUQ+MkyB8k+hYXCQw3S253LPuu1tdBVKAH+3uB/u3rJYmha/jdAqHyyzZBY2iAqTCvx5R7sfq491h+nX3wLbR9EZagks3YoilJV0KX9U8RI1554TrVujo2RJXD30CBni6mYSSudrpWKccVE9Cduz3hI/+KKjJOpNMvBRlEA93S0mu9O2JfzK3zWctOv5+gVXl+Ysz0f+lJelcA2zxI2r8aF7dXMRxtSUmJd+9AV/YF1Xzk6Rh602Lk1fK6t6E0qFeZ4lRnQvpke72yqcvx89ah098Ip1gphLuJLCliLQ2qREFERru32onnh05GNaKxTrSg7UUEqbMGe+jBpBenYjHPb7q3WSr1X+ZTaGnnhkYA1K6yLVm0wd70ZkDkPUAKc2tuuR6vtmCFw828qpna+21mjg7TJlZmzUYxnbKfmxlOOvzSXv6+qJXKXr7Z5QobCmviwDI+LEBPU6bt0Uzd6GkvjMQNayehJHHSvqzpeafynxkagZG1dTYsiYdTvblVcC1zegKPnzDQoVkO2ayBqS35caby0deRR4h7ISgxAEh1qY=
  app: floating-wave-88429
  on:
    repo: Btan579/Jam-Soon-Client
